# Generated by Django 2.2.1 on 2019-05-25 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('guest_count', models.IntegerField()),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('body', models.TextField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='reservation',
            name='pub_date',
            field=models.DateTimeField(verbose_name='data published'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
