# Generated by Django 2.2.1 on 2019-05-25 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_auto_20190525_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='store_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
